#!/bin/bash -e

if [ "${{ cookiecutter.project_slug|upper }}_DEBUG" = 'true' ]; then
    debug_args='--py-autoreload=2'
else
    debug_args=''
fi

uwsgi --http 0.0.0.0:${PORT:-5000} \
    --wsgi-file $APP_ROOT/{{ cookiecutter.project_slug }}/wsgi.py \
    --master \
    --callable app \
    --processes ${PROCESS_COUNT:-1} \
    --enable-threads \
    --threads ${THREAD_COUNT:-4} \
    --pythonpath $APP_ROOT \
    --need-app \
    ${debug_args}
